In [1]:
import pandas as pd
accepts =pd.read_csv ( 'accepts.csv' )
cross_table=pd.crosstab(accepts.bankruptcy_ind,accepts.bad_ind, margins=True)
cross_table

bad_ind            0     1   All
bankruptcy_ind
N               4163  1017  5180
Y                345   103   448
All             4508  1120  5628

In [2]:
cross_table_rowpct = cross_table.div(cross_table ["All"] ,axis = 0)
cross_table_rowpct

bad_ind                0         1  All
bankruptcy_ind
N               0.803668  0.196332  1.0
Y               0.770089  0.229911  1.0
All             0.800995  0.199005  1.0

In [3]:
# 打印结果
from scipy import stats
print(
    "chisq = %6.4f\np-value = %6.4f\ndof = %d\nexpected_freq = %s"
    %stats.chi2_contingency (cross_table))

chisq = 2.9167
p-value = 0.5719
dof = 4
expected_freq = [[4149.15422886 1030.84577114 5180.        ]
 [ 358.84577114   89.15422886  448.        ]
 [4508.         1120.         5628.        ]]