|变量名|变量含义|
|:--:|:--:|
|X1|品格：指客户的名誉|
|X2|能力：指客户的偿还能力|
|X3|资本：指客户的财务实力和财务状况|
|X4|担保：指对申请贷款项担保的覆盖程度|
|X5|环境：指外部经济、政策环境对客户的影响|

In [1]:
import pandas as pd
import numpy as np

raw_data = pd.read_csv("Loan_aply.csv",encoding='gbk')
raw_data.head()

   ID    X1    X2    X3    X4    X5
0   1  76.5  81.5  76.0  75.8  71.7
1   2  70.6  73.0  67.6  68.1  78.5
2   3  90.7  87.3  91.0  81.5  80.0
3   4  77.5  73.6  70.9  69.8  74.8
4   5  85.6  68.5  70.0  62.2  76.5

In [2]:
data = raw_data.loc[ :,'X1':]
data.corr(method='pearson')

          X1        X2        X3        X4        X5
X1  1.000000  0.726655  0.825342  0.676314  0.685563
X2  0.726655  1.000000  0.929080  0.938382  0.841413
X3  0.825342  0.929080  1.000000  0.883457  0.733482
X4  0.676314  0.938382  0.883457  1.000000  0.762563
X5  0.685563  0.841413  0.733482  0.762563  1.000000

In [3]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
pca = PCA(n_components=5)
pca.fit(scaled_data)

# 输出主成分可解释变异
print('Explained variance: \n', pca.explained_variance_)  
# 输出可解释变异的比例
print('Explained variance ratio:\n', pca.explained_variance_ratio_)

Explained variance:
 [4.67909448 0.42595504 0.33051612 0.0883994  0.03159051]
Explained variance ratio:
 [0.84223701 0.07667191 0.0594929  0.01591189 0.00568629]

In [4]:
# 打印主成分向量
print('Principal Components: \n', pca.components_)

Principal Components:
 [[ 0.41348998  0.47289329  0.46559941  0.45465337  0.42650378]
 [ 0.83489158 -0.27780163  0.14356811 -0.36209967 -0.27212927]
 [ 0.13234117 -0.13435628 -0.38238669 -0.36529569  0.82751053]
 [ 0.29048417 -0.27759393 -0.5960716   0.69246157 -0.06128758]
 [ 0.17345563  0.7772311  -0.51096423 -0.22187872 -0.23560632]]

- 说明：1、第一次的n_components参数应该设的大一点
- 说明：2、观察explained_variance_ratio_和explained_variance_的取值变化，建议explained_variance_ratio_累积大于0.85，explained_variance_需要保留的最后一个主成分大于0.8

In [5]:
scaled_data[0]

array([-0.26099897,  0.63617414,  0.19936295,  0.37986418, -0.44786189])

In [6]:
raw_data[['ID']].join(pd.DataFrame(pca.transform(scaled_data)))

   ID         0         1         2         3         4
0   1  0.267437 -0.381686 -0.705622 -0.080759  0.368551
1   2 -0.775172 -0.693877  0.730361 -0.085332  0.004801
2   3  2.603684  0.296977 -0.509037 -0.454156 -0.136519
3   4 -0.440204 -0.037307  0.198862  0.035171  0.066816
4   5 -0.678219  0.971254  0.889740 -0.101732 -0.037224
5   6  1.389937 -0.071514 -0.535472  0.535856 -0.260521
6   7  3.960102 -0.427956  0.610399  0.148751  0.081093
7   8 -1.310850  1.189789 -0.275763  0.264441  0.141813
8   9 -3.530640 -0.748477 -0.067092  0.143074 -0.074156
9  10 -1.486076 -0.097202 -0.336376 -0.405314 -0.154653

In [7]:
print('PCA_score of "ID=1":  %.4f'
      %np.dot(scaled_data[0], pca.components_[0]))

PCA_score of "ID=1":  0.2674

In [8]:
pca.set_params(n_components=1)
pca.fit(scaled_data)
data_pca = raw_data.join(
    pd.DataFrame(pca.transform(scaled_data), columns=['PCAScore']))

data_pca.head()

   ID    X1    X2    X3    X4    X5  PCAScore
0   1  76.5  81.5  76.0  75.8  71.7  0.267437
1   2  70.6  73.0  67.6  68.1  78.5 -0.775172
2   3  90.7  87.3  91.0  81.5  80.0  2.603684
3   4  77.5  73.6  70.9  69.8  74.8 -0.440204
4   5  85.6  68.5  70.0  62.2  76.5 -0.678219